name: Build and Package Course

on:
  push:
    branches: [main]
  release:
    types: [published]

jobs:
  build-scorm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout content repo
        uses: actions/checkout@v4

      - name: Create dist directory
        run: mkdir -p dist && chmod 0777 dist

      - name: Build Marp HTML
        uses: docker://marpteam/marp-cli:latest
        with:
          args: ipv6_training.md --html --allow-local-files --output dist/ipv6_training.html

